name: jrosarybibleapp
base: core22
adopt-info: metapart
version: '2.0.3'
summary: Read the Bible and other Christian texts. # 79 char long summary
description: |
  Study the Bible, and read Christianity related works. This projects goal is to promote spiritual health, and to allow each person to study the bible and come to their own conclusion about their faith.

grade: stable
confinement: strict

architectures:
   - build-on: [amd64]
     build-for: [amd64]
   - build-on: [arm64]
     build-for: [arm64]
   - build-on: [armhf]
     build for: [armhf]
apps:
  rosary:
    command: bin/rosary
    desktop: usr/share/applications/rosary.desktop

parts:
  prep:
    plugin: dump
    source:
      - on amd64 to amd64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.3/Rosary_2.0.3_amd64.deb
      - on arm64 to arm64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.3/Rosary_2.0.3_arm64.deb
      - on armhf to armhf: https://github.com/RoseBlume/Rosary/releases/download/v2.0.3/Rosary_2.0.3_armhf.deb
    source-type: deb
    override-pull: |
      set -eu
      craftctl default
      sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" usr/share/applications/rosary.desktop
    organize:
      usr/bin/rosary: bin/rosary
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libglu1-mesa
      - libsoup-3.0-0
      - freeglut3
