name: jrosarybibleapp
base: core22
adopt-info: metapart
version: '2.0.7'
summary: Read the Bible and other Christian texts. # 79 char long summary
description: |
  Study the Bible, and read Christianity related works. This projects goal is to promote spiritual health, and to allow each person to study the bible and come to their own conclusion about their faith.

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]

apps:
  rosary:
    command: bin/rosary
    desktop: usr/share/applications/rosary.desktop

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  prep:
    plugin: dump
    build-snaps:
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential 
      - curl 
      - wget 
      - file 
      - libxdo-dev 
      - libssl-dev 
      - libayatana-appindicator3-dev 
      - librsvg2-dev
      - dpkg
      - npm
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libglu1-mesa
      - libsoup-3.0-0
      - freeglut3-dev
    source: .
    #  - on amd64 to amd64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.4/Rosary_2.0.4_amd64.deb
    #  - on arm64 to arm64: https://github.com/RoseBlume/Rosary/releases/download/v2.0.4/Rosary_2.0.4_arm64.deb
    #  - on armhf to armhf: https://github.com/RoseBlume/Rosary/releases/download/v2.0.4/Rosary_2.0.4_armhf.deb
    #source-type: deb
    override-pull: |
      set -eu
      craftctl default
      npm install --force -g npm@latest
      npm install --force -g nodejs@latest
      rustup default nightly
      npm install
      cargo install --path src-tauri/
      cargo install tauri-cli --locked
      cargo tauri build --target aarch64-unknown-linux-gnu -b deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb here
      sed -i -e "s|Icon=rosary|Icon=/usr/share/icons/hicolor/32x32/apps/rosary.png|g" here/usr/share/applications/rosary.desktop
      cp -r here/* .
    organize:
      usr/bin/rosary: bin/rosary
