name: Raspberry Pi compile
on:
  workflow_dispatch:
env:
    VERSION: 2.0.5
jobs:
  build:
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
        - arch: armv6l
          cpu: arm1176
          deb: armhf
          base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Bookworm.img.xz
          cpu_info: raspberrypi_zero_w
        - arch: armv7l
          cpu: cortex-a72
          deb: armhf
          base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv7-Bookworm.img.xz
          cpu_info: raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a72
          base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bookworm.img.xz
          deb: arm64
          cpu_info: raspberrypi_zero2_w_arm64_w
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: false
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get upgrade -y
            apt-get autoremove -y
            apt-get install curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            # curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash
            # Install framework specific packages
            apt-get install -y nodejs
            apt-get install -y npm
            npm install -g npm@latest
            npm install -g node@latest
            # Install build tools and tauri-cli requirements
            apt-get install -y libwebkit2gtk-4.1-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
            # Install Rust Nightly
            rustup default nightly # Only Enable for nightly builds
            # Install frontend dependencies
            npm install
            # Build the application
            npm run tauri build
      - name: Upload deb bundle
        uses: actions/upload-artifact@v3
        with:
          name: Debian Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/deb/Rosary_${{ env.VERSION }}_${{ matrix.deb }}.deb
    